"""initial schema

Revision ID: e42386b50c0b
Revises: 
Create Date: 2026-08-29 01:11:21.826971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision = 'e42386b50c0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('videos',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('source_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('bvid', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('transcript_source', sa.String(length=16), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_videos_bvid', 'videos', ['bvid'], unique=False)
    op.create_index('idx_videos_user_created', 'videos', ['user_id', 'created_at'], unique=False)
    op.create_index('uk_user_source', 'videos', ['user_id', 'platform', 'source_hash'], unique=True)
    op.create_table('capsules',
    sa.Column('video_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('theme', sa.String(length=256), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('source_text_digest', sa.CHAR(length=64), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', name='uk_video')
    )
    op.create_index('idx_capsules_user_category', 'capsules', ['user_id', 'category'], unique=False)
    op.create_index('idx_capsules_user_created', 'capsules', ['user_id', 'created_at'], unique=False)
    op.create_table('extraction_tasks',
    sa.Column('video_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage_error', sa.String(length=512), nullable=True),
    sa.Column('retry_count', sa.SmallInteger(), nullable=False),
    sa.Column('raw_llm_output', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_status_updated', 'extraction_tasks', ['status', 'updated_at'], unique=False)
    op.create_index('idx_tasks_user_status', 'extraction_tasks', ['user_id', 'status', 'updated_at'], unique=False)
    op.create_index('idx_tasks_video', 'extraction_tasks', ['video_id'], unique=False)
    op.create_table('capsule_links',
    sa.Column('source_id', sa.BIGINT(), nullable=False),
    sa.Column('target_id', sa.BIGINT(), nullable=False),
    sa.Column('similarity', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['capsules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['capsules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', name='uk_edge')
    )
    op.create_index('idx_links_target', 'capsule_links', ['target_id'], unique=False)
    op.create_table('capsule_tags',
    sa.Column('capsule_id', sa.BIGINT(), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['capsule_id'], ['capsules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('capsule_id', 'tag'),
    sa.UniqueConstraint('capsule_id', 'tag', name='uk_capsule_tag')
    )
    op.create_table('embeddings',
    sa.Column('capsule_id', sa.BIGINT(), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('dim', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['capsule_id'], ['capsules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('capsule_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embeddings')
    op.drop_table('capsule_tags')
    op.drop_index('idx_links_target', table_name='capsule_links')
    op.drop_table('capsule_links')
    op.drop_index('idx_tasks_video', table_name='extraction_tasks')
    op.drop_index('idx_tasks_user_status', table_name='extraction_tasks')
    op.drop_index('idx_tasks_status_updated', table_name='extraction_tasks')
    op.drop_table('extraction_tasks')
    op.drop_index('idx_capsules_user_created', table_name='capsules')
    op.drop_index('idx_capsules_user_category', table_name='capsules')
    op.drop_table('capsules')
    op.drop_index('uk_user_source', table_name='videos')
    op.drop_index('idx_videos_user_created', table_name='videos')
    op.drop_index('idx_videos_bvid', table_name='videos')
    op.drop_table('videos')
    op.drop_table('users')
    # ### end Alembic commands ###
